# coding: utf-8

"""
    My Title

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.auth_base import AuthBase
from .models.auth_type import AuthType
from .models.card_comments_batch_update import CardCommentsBatchUpdate
from .models.card_type import CardType
from .models.comment_preview import CommentPreview
from .models.device import Device
from .models.device_type import DeviceType
from .models.error_code import ErrorCode
from .models.event_base import EventBase
from .models.event_type import EventType
from .models.event_version import EventVersion
from .models.list_of_resources_of_attendee import ListOfResourcesOfAttendee
from .models.list_of_resources_of_card_appointment import ListOfResourcesOfCardAppointment
from .models.list_of_resources_of_card_base import ListOfResourcesOfCardBase
from .models.list_of_resources_of_comment_base import ListOfResourcesOfCommentBase
from .models.list_of_resources_of_comment_chat import ListOfResourcesOfCommentChat
from .models.list_of_resources_of_comment_mail import ListOfResourcesOfCommentMail
from .models.list_of_resources_of_contact_base import ListOfResourcesOfContactBase
from .models.list_of_resources_of_event_base import ListOfResourcesOfEventBase
from .models.list_of_resources_of_file import ListOfResourcesOfFile
from .models.list_of_resources_of_group import ListOfResourcesOfGroup
from .models.list_of_resources_of_signature import ListOfResourcesOfSignature
from .models.list_of_resources_of_string import ListOfResourcesOfString
from .models.list_of_resources_of_tag import ListOfResourcesOfTag
from .models.list_of_resources_of_thumbnail_page import ListOfResourcesOfThumbnailPage
from .models.list_of_resources_of_user import ListOfResourcesOfUser
from .models.query_relation import QueryRelation
from .models.resource_base import ResourceBase
from .models.response import Response
from .models.response_type_model import ResponseTypeModel
from .models.sort_order import SortOrder
from .models.tag_type import TagType
from .models.thumbnail_info import ThumbnailInfo
from .models.thumbnail_page import ThumbnailPage
from .models.thumbnail_size import ThumbnailSize
from .models.token import Token
from .models.user_settings import UserSettings
from .models.user_status import UserStatus
from .models.appointment_response import AppointmentResponse
from .models.auth_exchange import AuthExchange
from .models.auth_google import AuthGoogle
from .models.auth_integration import AuthIntegration
from .models.auth_test import AuthTest
from .models.card_base import CardBase
from .models.comment_base import CommentBase
from .models.comment_body import CommentBody
from .models.contact_base import ContactBase
from .models.event_account_token_invalid import EventAccountTokenInvalid
from .models.event_card_created import EventCardCreated
from .models.event_card_updated import EventCardUpdated
from .models.event_comment_created import EventCommentCreated
from .models.event_contact_base import EventContactBase
from .models.event_list import EventList
from .models.event_signature_created import EventSignatureCreated
from .models.event_signature_deleted import EventSignatureDeleted
from .models.event_signature_updated import EventSignatureUpdated
from .models.event_tag_created import EventTagCreated
from .models.event_tag_deleted import EventTagDeleted
from .models.event_tag_updated import EventTagUpdated
from .models.event_tags_updated import EventTagsUpdated
from .models.event_user_onboarding_completed import EventUserOnboardingCompleted
from .models.event_user_registered import EventUserRegistered
from .models.event_user_status_changed import EventUserStatusChanged
from .models.file import File
from .models.list_of_tags import ListOfTags
from .models.response_conflict import ResponseConflict
from .models.signature import Signature
from .models.sync_settings_base import SyncSettingsBase
from .models.tag import Tag
from .models.card_appointment import CardAppointment
from .models.card_chat import CardChat
from .models.card_mail import CardMail
from .models.card_shared import CardShared
from .models.comment_chat import CommentChat
from .models.comment_mail import CommentMail
from .models.event_contact_created import EventContactCreated
from .models.event_contact_deleted import EventContactDeleted
from .models.event_contact_updated import EventContactUpdated
from .models.group import Group
from .models.sync_settings_exchange import SyncSettingsExchange
from .models.sync_settings_gmail import SyncSettingsGmail
from .models.user import User
from .models.attendee import Attendee

# import apis into sdk package
from .apis.auth_api import AuthApi
from .apis.card_api import CardApi
from .apis.comment_api import CommentApi
from .apis.contact_api import ContactApi
from .apis.device_api import DeviceApi
from .apis.event_api import EventApi
from .apis.file_api import FileApi
from .apis.group_api import GroupApi
from .apis.helper_api import HelperApi
from .apis.home_api import HomeApi
from .apis.settings_api import SettingsApi
from .apis.signature_api import SignatureApi
from .apis.tag_api import TagApi
from .apis.token_api import TokenApi
from .apis.user_api import UserApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
