# coding: utf-8

"""
    My Title

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CardAppointment(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'revision': 'str',
        'client_id': 'str',
        'type': 'str',
        'share_list': 'ListOfResourcesOfContactBase',
        'tags': 'ListOfTags',
        'created': 'datetime',
        'comments': 'ListOfResourcesOfCommentMail',
        'attendees': 'ListOfResourcesOfAttendee',
        'location': 'str',
        'start_time': 'datetime',
        'end_time': 'datetime',
        'is_all_day': 'bool',
        'is_cancelled': 'bool',
        'has_recurrence': 'bool',
        'is_occurrence': 'bool',
        'response': 'AppointmentResponse',
        'recurring_master_response': 'AppointmentResponse'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'revision': 'revision',
        'client_id': 'clientId',
        'type': '$type',
        'share_list': 'shareList',
        'tags': 'tags',
        'created': 'created',
        'comments': 'comments',
        'attendees': 'attendees',
        'location': 'location',
        'start_time': 'startTime',
        'end_time': 'endTime',
        'is_all_day': 'isAllDay',
        'is_cancelled': 'isCancelled',
        'has_recurrence': 'hasRecurrence',
        'is_occurrence': 'isOccurrence',
        'response': 'response',
        'recurring_master_response': 'recurringMasterResponse'
    }

    def __init__(self, id=None, name=None, revision=None, client_id=None, type=None, share_list=None, tags=None, created=None, comments=None, attendees=None, location=None, start_time=None, end_time=None, is_all_day=None, is_cancelled=None, has_recurrence=None, is_occurrence=None, response=None, recurring_master_response=None):
        """
        CardAppointment - a model defined in Swagger
        """

        self._id = None
        self._name = None
        self._revision = None
        self._client_id = None
        self._type = None
        self._share_list = None
        self._tags = None
        self._created = None
        self._comments = None
        self._attendees = None
        self._location = None
        self._start_time = None
        self._end_time = None
        self._is_all_day = None
        self._is_cancelled = None
        self._has_recurrence = None
        self._is_occurrence = None
        self._response = None
        self._recurring_master_response = None

        if id is not None:
          self.id = id
        if name is not None:
          self.name = name
        if revision is not None:
          self.revision = revision
        if client_id is not None:
          self.client_id = client_id
        self.type = type
        if share_list is not None:
          self.share_list = share_list
        if tags is not None:
          self.tags = tags
        if created is not None:
          self.created = created
        if comments is not None:
          self.comments = comments
        if attendees is not None:
          self.attendees = attendees
        if location is not None:
          self.location = location
        if start_time is not None:
          self.start_time = start_time
        if end_time is not None:
          self.end_time = end_time
        if is_all_day is not None:
          self.is_all_day = is_all_day
        if is_cancelled is not None:
          self.is_cancelled = is_cancelled
        if has_recurrence is not None:
          self.has_recurrence = has_recurrence
        if is_occurrence is not None:
          self.is_occurrence = is_occurrence
        if response is not None:
          self.response = response
        if recurring_master_response is not None:
          self.recurring_master_response = recurring_master_response

    @property
    def id(self):
        """
        Gets the id of this CardAppointment.
        Resource id

        :return: The id of this CardAppointment.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this CardAppointment.
        Resource id

        :param id: The id of this CardAppointment.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this CardAppointment.
        Resource name or title

        :return: The name of this CardAppointment.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this CardAppointment.
        Resource name or title

        :param name: The name of this CardAppointment.
        :type: str
        """

        self._name = name

    @property
    def revision(self):
        """
        Gets the revision of this CardAppointment.
        Resource revision

        :return: The revision of this CardAppointment.
        :rtype: str
        """
        return self._revision

    @revision.setter
    def revision(self, revision):
        """
        Sets the revision of this CardAppointment.
        Resource revision

        :param revision: The revision of this CardAppointment.
        :type: str
        """

        self._revision = revision

    @property
    def client_id(self):
        """
        Gets the client_id of this CardAppointment.
        Resource client id

        :return: The client_id of this CardAppointment.
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """
        Sets the client_id of this CardAppointment.
        Resource client id

        :param client_id: The client_id of this CardAppointment.
        :type: str
        """

        self._client_id = client_id

    @property
    def type(self):
        """
        Gets the type of this CardAppointment.

        :return: The type of this CardAppointment.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this CardAppointment.

        :param type: The type of this CardAppointment.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def share_list(self):
        """
        Gets the share_list of this CardAppointment.
        List of contacts that take part on the card

        :return: The share_list of this CardAppointment.
        :rtype: ListOfResourcesOfContactBase
        """
        return self._share_list

    @share_list.setter
    def share_list(self, share_list):
        """
        Sets the share_list of this CardAppointment.
        List of contacts that take part on the card

        :param share_list: The share_list of this CardAppointment.
        :type: ListOfResourcesOfContactBase
        """

        self._share_list = share_list

    @property
    def tags(self):
        """
        Gets the tags of this CardAppointment.
        Tags reference on card

        :return: The tags of this CardAppointment.
        :rtype: ListOfTags
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """
        Sets the tags of this CardAppointment.
        Tags reference on card

        :param tags: The tags of this CardAppointment.
        :type: ListOfTags
        """

        self._tags = tags

    @property
    def created(self):
        """
        Gets the created of this CardAppointment.
        Time of card creation

        :return: The created of this CardAppointment.
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """
        Sets the created of this CardAppointment.
        Time of card creation

        :param created: The created of this CardAppointment.
        :type: datetime
        """

        self._created = created

    @property
    def comments(self):
        """
        Gets the comments of this CardAppointment.
        List of comments

        :return: The comments of this CardAppointment.
        :rtype: ListOfResourcesOfCommentMail
        """
        return self._comments

    @comments.setter
    def comments(self, comments):
        """
        Sets the comments of this CardAppointment.
        List of comments

        :param comments: The comments of this CardAppointment.
        :type: ListOfResourcesOfCommentMail
        """

        self._comments = comments

    @property
    def attendees(self):
        """
        Gets the attendees of this CardAppointment.
        List of appointment attendees

        :return: The attendees of this CardAppointment.
        :rtype: ListOfResourcesOfAttendee
        """
        return self._attendees

    @attendees.setter
    def attendees(self, attendees):
        """
        Sets the attendees of this CardAppointment.
        List of appointment attendees

        :param attendees: The attendees of this CardAppointment.
        :type: ListOfResourcesOfAttendee
        """

        self._attendees = attendees

    @property
    def location(self):
        """
        Gets the location of this CardAppointment.
        Appointment location

        :return: The location of this CardAppointment.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location):
        """
        Sets the location of this CardAppointment.
        Appointment location

        :param location: The location of this CardAppointment.
        :type: str
        """

        self._location = location

    @property
    def start_time(self):
        """
        Gets the start_time of this CardAppointment.
        Appointment start time (is set to midnight if it is all day)

        :return: The start_time of this CardAppointment.
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """
        Sets the start_time of this CardAppointment.
        Appointment start time (is set to midnight if it is all day)

        :param start_time: The start_time of this CardAppointment.
        :type: datetime
        """

        self._start_time = start_time

    @property
    def end_time(self):
        """
        Gets the end_time of this CardAppointment.
        Appointment end time (is set to midnight if it is all day)

        :return: The end_time of this CardAppointment.
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """
        Sets the end_time of this CardAppointment.
        Appointment end time (is set to midnight if it is all day)

        :param end_time: The end_time of this CardAppointment.
        :type: datetime
        """

        self._end_time = end_time

    @property
    def is_all_day(self):
        """
        Gets the is_all_day of this CardAppointment.
        Flag indicating whether the appointment is all day

        :return: The is_all_day of this CardAppointment.
        :rtype: bool
        """
        return self._is_all_day

    @is_all_day.setter
    def is_all_day(self, is_all_day):
        """
        Sets the is_all_day of this CardAppointment.
        Flag indicating whether the appointment is all day

        :param is_all_day: The is_all_day of this CardAppointment.
        :type: bool
        """

        self._is_all_day = is_all_day

    @property
    def is_cancelled(self):
        """
        Gets the is_cancelled of this CardAppointment.
        Flag indicating whether the appointment was cancelled

        :return: The is_cancelled of this CardAppointment.
        :rtype: bool
        """
        return self._is_cancelled

    @is_cancelled.setter
    def is_cancelled(self, is_cancelled):
        """
        Sets the is_cancelled of this CardAppointment.
        Flag indicating whether the appointment was cancelled

        :param is_cancelled: The is_cancelled of this CardAppointment.
        :type: bool
        """

        self._is_cancelled = is_cancelled

    @property
    def has_recurrence(self):
        """
        Gets the has_recurrence of this CardAppointment.
        Flag indicating whether the appointment is recurring master

        :return: The has_recurrence of this CardAppointment.
        :rtype: bool
        """
        return self._has_recurrence

    @has_recurrence.setter
    def has_recurrence(self, has_recurrence):
        """
        Sets the has_recurrence of this CardAppointment.
        Flag indicating whether the appointment is recurring master

        :param has_recurrence: The has_recurrence of this CardAppointment.
        :type: bool
        """

        self._has_recurrence = has_recurrence

    @property
    def is_occurrence(self):
        """
        Gets the is_occurrence of this CardAppointment.
        Flag indication whether the RSVP is only one instance of a recurring appointment

        :return: The is_occurrence of this CardAppointment.
        :rtype: bool
        """
        return self._is_occurrence

    @is_occurrence.setter
    def is_occurrence(self, is_occurrence):
        """
        Sets the is_occurrence of this CardAppointment.
        Flag indication whether the RSVP is only one instance of a recurring appointment

        :param is_occurrence: The is_occurrence of this CardAppointment.
        :type: bool
        """

        self._is_occurrence = is_occurrence

    @property
    def response(self):
        """
        Gets the response of this CardAppointment.
        Authorized user's response to the appointment

        :return: The response of this CardAppointment.
        :rtype: AppointmentResponse
        """
        return self._response

    @response.setter
    def response(self, response):
        """
        Sets the response of this CardAppointment.
        Authorized user's response to the appointment

        :param response: The response of this CardAppointment.
        :type: AppointmentResponse
        """

        self._response = response

    @property
    def recurring_master_response(self):
        """
        Gets the recurring_master_response of this CardAppointment.
        Authorized user's response to the entire recurring appointment (set only if this appointment is an instance of a recurring appointment)

        :return: The recurring_master_response of this CardAppointment.
        :rtype: AppointmentResponse
        """
        return self._recurring_master_response

    @recurring_master_response.setter
    def recurring_master_response(self, recurring_master_response):
        """
        Sets the recurring_master_response of this CardAppointment.
        Authorized user's response to the entire recurring appointment (set only if this appointment is an instance of a recurring appointment)

        :param recurring_master_response: The recurring_master_response of this CardAppointment.
        :type: AppointmentResponse
        """

        self._recurring_master_response = recurring_master_response

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CardAppointment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
