# coding: utf-8

"""
    My Title

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Tag(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'revision': 'str',
        'client_id': 'str',
        'type': 'str',
        'tag_type': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'revision': 'revision',
        'client_id': 'clientId',
        'type': '$type',
        'tag_type': 'tagType'
    }

    def __init__(self, id=None, name=None, revision=None, client_id=None, type=None, tag_type=None):
        """
        Tag - a model defined in Swagger
        """

        self._id = None
        self._name = None
        self._revision = None
        self._client_id = None
        self._type = None
        self._tag_type = None

        if id is not None:
          self.id = id
        if name is not None:
          self.name = name
        if revision is not None:
          self.revision = revision
        if client_id is not None:
          self.client_id = client_id
        self.type = type
        if tag_type is not None:
          self.tag_type = tag_type

    @property
    def id(self):
        """
        Gets the id of this Tag.
        Resource id

        :return: The id of this Tag.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Tag.
        Resource id

        :param id: The id of this Tag.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this Tag.
        Resource name or title

        :return: The name of this Tag.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Tag.
        Resource name or title

        :param name: The name of this Tag.
        :type: str
        """

        self._name = name

    @property
    def revision(self):
        """
        Gets the revision of this Tag.
        Resource revision

        :return: The revision of this Tag.
        :rtype: str
        """
        return self._revision

    @revision.setter
    def revision(self, revision):
        """
        Sets the revision of this Tag.
        Resource revision

        :param revision: The revision of this Tag.
        :type: str
        """

        self._revision = revision

    @property
    def client_id(self):
        """
        Gets the client_id of this Tag.
        Resource client id

        :return: The client_id of this Tag.
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """
        Sets the client_id of this Tag.
        Resource client id

        :param client_id: The client_id of this Tag.
        :type: str
        """

        self._client_id = client_id

    @property
    def type(self):
        """
        Gets the type of this Tag.

        :return: The type of this Tag.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this Tag.

        :param type: The type of this Tag.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def tag_type(self):
        """
        Gets the tag_type of this Tag.
        Tag type. If TagType is the same as Id, that means that this is a system board and can not be altered by clients

        :return: The tag_type of this Tag.
        :rtype: str
        """
        return self._tag_type

    @tag_type.setter
    def tag_type(self, tag_type):
        """
        Sets the tag_type of this Tag.
        Tag type. If TagType is the same as Id, that means that this is a system board and can not be altered by clients

        :param tag_type: The tag_type of this Tag.
        :type: str
        """

        self._tag_type = tag_type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Tag):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
