# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AuthIntegration(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'token': 'Token',
        'type': 'str',
        'identificator': 'str',
        'secret': 'str'
    }

    attribute_map = {
        'token': 'token',
        'type': '$type',
        'identificator': 'identificator',
        'secret': 'secret'
    }

    def __init__(self, token=None, type=None, identificator=None, secret=None):
        """
        AuthIntegration - a model defined in Swagger
        """

        self._token = None
        self._type = None
        self._identificator = None
        self._secret = None

        if token is not None:
          self.token = token
        self.type = type
        if identificator is not None:
          self.identificator = identificator
        if secret is not None:
          self.secret = secret

    @property
    def token(self):
        """
        Gets the token of this AuthIntegration.

        :return: The token of this AuthIntegration.
        :rtype: Token
        """
        return self._token

    @token.setter
    def token(self, token):
        """
        Sets the token of this AuthIntegration.

        :param token: The token of this AuthIntegration.
        :type: Token
        """

        self._token = token

    @property
    def type(self):
        """
        Gets the type of this AuthIntegration.

        :return: The type of this AuthIntegration.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this AuthIntegration.

        :param type: The type of this AuthIntegration.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def identificator(self):
        """
        Gets the identificator of this AuthIntegration.

        :return: The identificator of this AuthIntegration.
        :rtype: str
        """
        return self._identificator

    @identificator.setter
    def identificator(self, identificator):
        """
        Sets the identificator of this AuthIntegration.

        :param identificator: The identificator of this AuthIntegration.
        :type: str
        """

        self._identificator = identificator

    @property
    def secret(self):
        """
        Gets the secret of this AuthIntegration.

        :return: The secret of this AuthIntegration.
        :rtype: str
        """
        return self._secret

    @secret.setter
    def secret(self, secret):
        """
        Sets the secret of this AuthIntegration.

        :param secret: The secret of this AuthIntegration.
        :type: str
        """

        self._secret = secret

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AuthIntegration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
