# coding: utf-8

"""
    My Title

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CardMail(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'revision': 'str',
        'client_id': 'str',
        'type': 'str',
        'share_list': 'ListOfResourcesOfContactBase',
        'tags': 'ListOfTags',
        'created': 'datetime',
        'comments': 'ListOfResourcesOfCommentMail',
        'copied_card_ids': 'ListOfResourcesOfString',
        'appointment_link': 'CardAppointment',
        'snapshot_resource': 'ResourceBase'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'revision': 'revision',
        'client_id': 'clientId',
        'type': '$type',
        'share_list': 'shareList',
        'tags': 'tags',
        'created': 'created',
        'comments': 'comments',
        'copied_card_ids': 'copiedCardIds',
        'appointment_link': 'appointmentLink',
        'snapshot_resource': 'snapshotResource'
    }

    def __init__(self, id=None, name=None, revision=None, client_id=None, type=None, share_list=None, tags=None, created=None, comments=None, copied_card_ids=None, appointment_link=None, snapshot_resource=None):
        """
        CardMail - a model defined in Swagger
        """

        self._id = None
        self._name = None
        self._revision = None
        self._client_id = None
        self._type = None
        self._share_list = None
        self._tags = None
        self._created = None
        self._comments = None
        self._copied_card_ids = None
        self._appointment_link = None
        self._snapshot_resource = None

        if id is not None:
          self.id = id
        if name is not None:
          self.name = name
        if revision is not None:
          self.revision = revision
        if client_id is not None:
          self.client_id = client_id
        self.type = type
        if share_list is not None:
          self.share_list = share_list
        if tags is not None:
          self.tags = tags
        if created is not None:
          self.created = created
        if comments is not None:
          self.comments = comments
        if copied_card_ids is not None:
          self.copied_card_ids = copied_card_ids
        if appointment_link is not None:
          self.appointment_link = appointment_link
        if snapshot_resource is not None:
          self.snapshot_resource = snapshot_resource

    @property
    def id(self):
        """
        Gets the id of this CardMail.
        Resource id

        :return: The id of this CardMail.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this CardMail.
        Resource id

        :param id: The id of this CardMail.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this CardMail.
        Resource name or title

        :return: The name of this CardMail.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this CardMail.
        Resource name or title

        :param name: The name of this CardMail.
        :type: str
        """

        self._name = name

    @property
    def revision(self):
        """
        Gets the revision of this CardMail.
        Resource revision

        :return: The revision of this CardMail.
        :rtype: str
        """
        return self._revision

    @revision.setter
    def revision(self, revision):
        """
        Sets the revision of this CardMail.
        Resource revision

        :param revision: The revision of this CardMail.
        :type: str
        """

        self._revision = revision

    @property
    def client_id(self):
        """
        Gets the client_id of this CardMail.
        Resource client id

        :return: The client_id of this CardMail.
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """
        Sets the client_id of this CardMail.
        Resource client id

        :param client_id: The client_id of this CardMail.
        :type: str
        """

        self._client_id = client_id

    @property
    def type(self):
        """
        Gets the type of this CardMail.

        :return: The type of this CardMail.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this CardMail.

        :param type: The type of this CardMail.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def share_list(self):
        """
        Gets the share_list of this CardMail.
        List of contacts that take part on the card

        :return: The share_list of this CardMail.
        :rtype: ListOfResourcesOfContactBase
        """
        return self._share_list

    @share_list.setter
    def share_list(self, share_list):
        """
        Sets the share_list of this CardMail.
        List of contacts that take part on the card

        :param share_list: The share_list of this CardMail.
        :type: ListOfResourcesOfContactBase
        """

        self._share_list = share_list

    @property
    def tags(self):
        """
        Gets the tags of this CardMail.
        Tags reference on card

        :return: The tags of this CardMail.
        :rtype: ListOfTags
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """
        Sets the tags of this CardMail.
        Tags reference on card

        :param tags: The tags of this CardMail.
        :type: ListOfTags
        """

        self._tags = tags

    @property
    def created(self):
        """
        Gets the created of this CardMail.
        Time of card creation

        :return: The created of this CardMail.
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """
        Sets the created of this CardMail.
        Time of card creation

        :param created: The created of this CardMail.
        :type: datetime
        """

        self._created = created

    @property
    def comments(self):
        """
        Gets the comments of this CardMail.
        List of comments

        :return: The comments of this CardMail.
        :rtype: ListOfResourcesOfCommentMail
        """
        return self._comments

    @comments.setter
    def comments(self, comments):
        """
        Sets the comments of this CardMail.
        List of comments

        :param comments: The comments of this CardMail.
        :type: ListOfResourcesOfCommentMail
        """

        self._comments = comments

    @property
    def copied_card_ids(self):
        """
        Gets the copied_card_ids of this CardMail.
        List of ids for shared cards created (copied) from this card.

        :return: The copied_card_ids of this CardMail.
        :rtype: ListOfResourcesOfString
        """
        return self._copied_card_ids

    @copied_card_ids.setter
    def copied_card_ids(self, copied_card_ids):
        """
        Sets the copied_card_ids of this CardMail.
        List of ids for shared cards created (copied) from this card.

        :param copied_card_ids: The copied_card_ids of this CardMail.
        :type: ListOfResourcesOfString
        """

        self._copied_card_ids = copied_card_ids

    @property
    def appointment_link(self):
        """
        Gets the appointment_link of this CardMail.
        Link between corresponding CardMail and CardAppointment

        :return: The appointment_link of this CardMail.
        :rtype: CardAppointment
        """
        return self._appointment_link

    @appointment_link.setter
    def appointment_link(self, appointment_link):
        """
        Sets the appointment_link of this CardMail.
        Link between corresponding CardMail and CardAppointment

        :param appointment_link: The appointment_link of this CardMail.
        :type: CardAppointment
        """

        self._appointment_link = appointment_link

    @property
    def snapshot_resource(self):
        """
        Gets the snapshot_resource of this CardMail.
        Snapshot resource that this one was copied from.

        :return: The snapshot_resource of this CardMail.
        :rtype: ResourceBase
        """
        return self._snapshot_resource

    @snapshot_resource.setter
    def snapshot_resource(self, snapshot_resource):
        """
        Sets the snapshot_resource of this CardMail.
        Snapshot resource that this one was copied from.

        :param snapshot_resource: The snapshot_resource of this CardMail.
        :type: ResourceBase
        """

        self._snapshot_resource = snapshot_resource

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CardMail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
