# coding: utf-8

"""
    My Title

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ContactBase(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'revision': 'str',
        'client_id': 'str',
        'type': 'str',
        'tags': 'ListOfTags',
        'weight': 'float'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'revision': 'revision',
        'client_id': 'clientId',
        'type': '$type',
        'tags': 'tags',
        'weight': 'weight'
    }

    def __init__(self, id=None, name=None, revision=None, client_id=None, type=None, tags=None, weight=None):
        """
        ContactBase - a model defined in Swagger
        """

        self._id = None
        self._name = None
        self._revision = None
        self._client_id = None
        self._type = None
        self._tags = None
        self._weight = None

        if id is not None:
          self.id = id
        if name is not None:
          self.name = name
        if revision is not None:
          self.revision = revision
        if client_id is not None:
          self.client_id = client_id
        self.type = type
        if tags is not None:
          self.tags = tags
        if weight is not None:
          self.weight = weight

    @property
    def id(self):
        """
        Gets the id of this ContactBase.
        Resource id

        :return: The id of this ContactBase.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ContactBase.
        Resource id

        :param id: The id of this ContactBase.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this ContactBase.
        Resource name or title

        :return: The name of this ContactBase.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ContactBase.
        Resource name or title

        :param name: The name of this ContactBase.
        :type: str
        """

        self._name = name

    @property
    def revision(self):
        """
        Gets the revision of this ContactBase.
        Resource revision

        :return: The revision of this ContactBase.
        :rtype: str
        """
        return self._revision

    @revision.setter
    def revision(self, revision):
        """
        Sets the revision of this ContactBase.
        Resource revision

        :param revision: The revision of this ContactBase.
        :type: str
        """

        self._revision = revision

    @property
    def client_id(self):
        """
        Gets the client_id of this ContactBase.
        Resource client id

        :return: The client_id of this ContactBase.
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """
        Sets the client_id of this ContactBase.
        Resource client id

        :param client_id: The client_id of this ContactBase.
        :type: str
        """

        self._client_id = client_id

    @property
    def type(self):
        """
        Gets the type of this ContactBase.

        :return: The type of this ContactBase.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this ContactBase.

        :param type: The type of this ContactBase.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def tags(self):
        """
        Gets the tags of this ContactBase.
        Tags reference on contact

        :return: The tags of this ContactBase.
        :rtype: ListOfTags
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """
        Sets the tags of this ContactBase.
        Tags reference on contact

        :param tags: The tags of this ContactBase.
        :type: ListOfTags
        """

        self._tags = tags

    @property
    def weight(self):
        """
        Gets the weight of this ContactBase.
        Usage weight.

        :return: The weight of this ContactBase.
        :rtype: float
        """
        return self._weight

    @weight.setter
    def weight(self, weight):
        """
        Sets the weight of this ContactBase.
        Usage weight.

        :param weight: The weight of this ContactBase.
        :type: float
        """

        self._weight = weight

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ContactBase):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
