# coding: utf-8

"""
    My Title

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Device(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'device_type': 'str',
        'api_version': 'str',
        'push_notification_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'device_type': 'deviceType',
        'api_version': 'apiVersion',
        'push_notification_id': 'pushNotificationId'
    }

    def __init__(self, id=None, name=None, device_type=None, api_version=None, push_notification_id=None):
        """
        Device - a model defined in Swagger
        """

        self._id = None
        self._name = None
        self._device_type = None
        self._api_version = None
        self._push_notification_id = None

        if id is not None:
          self.id = id
        if name is not None:
          self.name = name
        if device_type is not None:
          self.device_type = device_type
        if api_version is not None:
          self.api_version = api_version
        if push_notification_id is not None:
          self.push_notification_id = push_notification_id

    @property
    def id(self):
        """
        Gets the id of this Device.
        Device id

        :return: The id of this Device.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Device.
        Device id

        :param id: The id of this Device.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this Device.
        Device name

        :return: The name of this Device.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Device.
        Device name

        :param name: The name of this Device.
        :type: str
        """

        self._name = name

    @property
    def device_type(self):
        """
        Gets the device_type of this Device.
        Device type (all possible device types are listed under enums/DeviceType)

        :return: The device_type of this Device.
        :rtype: str
        """
        return self._device_type

    @device_type.setter
    def device_type(self, device_type):
        """
        Sets the device_type of this Device.
        Device type (all possible device types are listed under enums/DeviceType)

        :param device_type: The device_type of this Device.
        :type: str
        """

        self._device_type = device_type

    @property
    def api_version(self):
        """
        Gets the api_version of this Device.
        Api version (all possible device types are listed under enums/EventVersion)

        :return: The api_version of this Device.
        :rtype: str
        """
        return self._api_version

    @api_version.setter
    def api_version(self, api_version):
        """
        Sets the api_version of this Device.
        Api version (all possible device types are listed under enums/EventVersion)

        :param api_version: The api_version of this Device.
        :type: str
        """

        self._api_version = api_version

    @property
    def push_notification_id(self):
        """
        Gets the push_notification_id of this Device.
        Push notification id

        :return: The push_notification_id of this Device.
        :rtype: str
        """
        return self._push_notification_id

    @push_notification_id.setter
    def push_notification_id(self, push_notification_id):
        """
        Sets the push_notification_id of this Device.
        Push notification id

        :param push_notification_id: The push_notification_id of this Device.
        :type: str
        """

        self._push_notification_id = push_notification_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Device):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
